### ISSUE TITLE
Building a web-based manual

### ISSUE THREAD

**Issue by aaanh** [NAG-DevOps/speed-hpc#19]
Hi NAG team,

I would like to propose about how the manual could be made more accessible for users by hosting the content on a web-based manual. 

The manual would be written in markdown and compiled into static HTML/CSS/JS bundles by a static site generator (I recommend Rust-based [mdbook](https://rust-lang.github.io/mdBook/)) and served by a simple web server like `nginx` or `apache2` without the need for additional configurations. I think this setup (with Apache2) would fit nicely on our server environment.

From the user's perspective, aside from the common markdown specifications, the web-based manual can accommodate sections and subsections with dynamically-linked table of contents. Code blocks are syntax highlighted and can be copied to clipboard with a button.

To improve the authoring process, we could set up Github Actions to watch for source changes then automatically compile and push static artifacts to the destination web-root folder through `rsync` or `scp`.
For demo, I have mine set up at <https://users.encs.concordia.ca/~a_en201>.

What I have not fully figured out is how we can automate updating the content from the Latex source to the Markdown source yet.

What do you think?

**Comment by aaanh** [comment]
Got it, yes, I understand the bibliography management would be a major issue with markdown. So, as you said, probably the most preferred method is to compile directly from Latex to HTML. 
I have tried using `pandoc` for the conversion but seems like there are a lot left to be desired and experimented on. One issue I've seen is that the author metadata is not rendered despite the different combinations of options I tried. I'll look into it more. Another idea is to convert from the PDF to HTML using `pdftohtml` but that lacks proper styling and layout.

**Comment by aaanh** [comment]
Hi again, I have managed to build a pipeline using Github Actions to deploy to github.io for serving the static HTML output. So far, the output is formatted with LaTeX and bibliography and references are rendered correctly.
You can view the running demo here: <https://aaanh.github.io/speed-hpc>
For the Github Actions workflow, you can inspect the `yml` file here: <https://github.com/aaanh/speed-hpc/blob/html-render/.github/workflows/deploy-static.yml>. I have not gone so far as to build the HTML on Github Actions, but I added an option in the Makefile to compile locally using the `make4ht` tool.

**Comment by aaanh** [comment]
- For point 1, looks like the figure styling comes from `make4ht` default semantic CSS `text-align: center`. I firefight by simply replacing it with `sed` as a post-build step. I'll be looking into a less hacky configuration.
- For point 2, I have added 2 additional LaTeX passes after BibTex as you have suggested and it works! Now, it is able to resolve all the references. Personally, this is the first time I am aware of the effect of passes and now I'm reading up more about that process.
- I think the build system does something funny with the LaTeX `file` command, as other `\_`'s, including the verbatims, are able to escape. I'll try by removing the escapes from the `file` command to see.
- Yes, the source of the error is in the `.tex` source with ``` ``moment'' ``` (x2 backticks + x2 apos)
- For this, if we don't want to modify the `file` command itself, I can see a hacky way by using JavaScript to query the elements and insert the repository's static blob link into the hyperlinks so that it points directly to the script's file. But I think it's best to modify the `file` command because the `.pdf` output refers to these links by the contextual directory of where it is downloaded to anyway, so it wouldn't negatively affect what we currently have on the main `HEAD`.

**Comment by aaanh** [comment]
The updated output with the fixes is live at: <https://aaanh.github.io/speed-hpc/>

It contains the following fixes:
- Fixed textual figure alignment by setting the CSS configuration for `make4ht`.
- Fixed null bibliography references
- Removed the escaped underscores
- Fixed the rendered escaped HTML code when using absolute path with `file` command by replacing with `\verb` instead.

**Comment by smokhov** [comment]
Thanks for the fixes Anh so far. A few comments and questions:

- 2x backticks and apostrophes are a standed LaTeXy way to create opening and closing double quotes. We use it throughout. regular double quotes are not proper ones to use in LaTeX sources for this issue.
- Reviewing [diff and file changes](https://github.com/NAG-DevOps/speed-hpc/compare/master...aaanh:speed-hpc:master), I have a few concerns: there is a large number of unrelated changes it seems that appear to be no-changes at all -- where whole-file-diffs are produced where there are apparently no changes but all of the file is diffed. This suggests line endings differences were committed. Many files have such changes, the problem appears to have been [here](https://github.com/NAG-DevOps/speed-hpc/commit/aa916488ce6cdc66d8e8354afccda9d30005e53c#diff-a6a98674bedb208ab6947c2fb46dd523788d1051130cabdc24847a007f474735). If your git does not set proper line endings back and forth if working on Windows, need to change its settings.

**Comment by aaanh** [comment]
Thank you for the review!

- I'll put back the standard LaTeX backticks. I totally did not know that it was a thing. So, I guess we can pinpoint it more directly to how `make4ht` deals with the `\file` command.
- Yes, that is most likely the case because I was trying to squash some trivial commits when I was testing out Github Actions and other HTML build systems. I will work to have those no-change commits reverted, along with the additions/deletions of artifacts dropped.

**Comment by aaanh** [comment]
I have rewritten the git history beginning from the latest upstream commit and cleaned up the commits to be more concise.

I achieved that by doing a hard reset and redoing the significant commits on a Unix environment instead of Windows to avoid the line ending problem, unnecessary build artifacts being committed, and the complicated rebases.

Side note: Would you also like to merge my `.devcontainers` folder into upstream? [Dev Container is a VS Code feature](https://code.visualstudio.com/docs/devcontainers/containers) that starts a Docker container with the tools and configurations, which is basically a remote development environment. I have configured it to start up a full-fledged LaTeX authoring environment.

**Comment by yulgroper** [comment]
Hi Anh, 

An HTML manual will be easier for cllients to navigate. Good thinking.

I also use VS Code. Thank you for suggesting the dev container app. As it is not necessary to use VS Code to update the speed-manual-tex file, I suggest adding your .devcontainer folder to a new directory, e.g.,  speed-hpc/utils.

**Comment by yulgroper** [comment]
I just learnt more above the Dev Container extension. From what I understand, the .devcontainers folder would need to be in the speed-hpc/doc directory so please ignore my previous commend re a new utils directory.

**Comment by aaanh** [comment]
Hi Gillian,

Thank you for your feedback! I'll go ahead and make the adjustments as you have suggested, then I'll start a PR for the changes. For Github Actions to deploy to Github Pages, it will need to be enabled first in the repository settings.

Steps to enable (I also put the details in a `README.md` in the `.github` folder for future references):
- At repository homepage on Github, select **Settings** tab.
- On the sidebar, select the **Pages** subsection.
- Under **Build and Deployment** &gt; Source, select Github Actions from the dropdown menu.

**Comment by smokhov** [comment]
Anh thanks for the PR! Sorry I did not jump on this sooner. Did you try compiling the manual after the changes? It produces 20 errors. The `\_` in `\file{}` has to stay. We need a post-processing step instead to strip it in HTML.

**Comment by smokhov** [comment]
Also

> For Github Actions to deploy to Github Pages, it will need to be enabled first in the repository settings.

We can't really enable it first until there is something there; it will ask creating a fresh new workflow based either on Jekyll or static; which will then conflict with the PR if added. So I will enable those after the PR is merged instead.

**Comment by aaanh** [comment]
Hi Serguei, thank you very much for having reviewed it. I have reverted the `\_` escape on my local copy and will figure out a post-processing step, maybe by using a `sed` script to remove them in the output HTML.

For the remaining errors, I fixed it by changing the `\verb` in

> 818 | and/or by examining the ``moment'' file in 
> 819 | \texttt{/disk/nobackup/<yourjob>}

to `\texttt` instead. That was due to my oversight and didn't check the linting for the PDF build properly.

**Comment by aaanh** [comment]
I also have re-verified that the `.devcontainer` folder would need to be at repository root in order to have the necessary references in `/src` for the manual to build. If such repo structure is not desired, I could simply drop the folder until there's a better way of doing it.

**Comment by smokhov** [comment]
We want `.devcontainer`; but can't it look at `../src` instead or if a symlink to `../src` while building can work?

**Comment by aaanh** [comment]
I think the problem is how VS Code auto-detects the existence of a `.devcontainer/` which includes the `devcontainer.json` with the build directives for the containers. 

But building on that knowledge, I managed to figure out a workaround to simply point the mounted volume of the remote workspace to the project root directory, as in `../../` in the `docker-compose.yml` and tested to be working.

I dug a little deeper into how VS Code handles `.devcontainer` and found that it is still [an ongoing limitation](https://github.com/microsoft/vscode-remote-release/issues/2413) they have not addressed. So the manual change above needs to be made.
